### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by miguelmaso** [miguelmaso/dynamics#13]
- [ ] Style review
- [ ] [SDOF] forced vibration of slab
- [ ] [SDOF] train over bridge
- [ ] [MDOF] multimodal shear building
- [ ] [MDOF] simplified shear building
- [ ] [ipynb] Add explanations
